; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Dday Normandy"
#define MyAppVersion "AUTO_INJECTED_BY_WORKFLOW"
#define MyAppPublisher "Dday Normandy Chile "
#define MyAppURL "https://www.dday.cl"
#define MyAppExeName "Quake2.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
; #define IncludeDiscordSDK      ; discord_game_sdk.dll
; #define IncludeAvFormat        ; avformat-63.dll
; #define IncludeAvCodec         ; avcodec-63.dll
; #define IncludeAvUtil          ; avutil-61.dll
; #define IncludeAvFilter        ; avfilter-12.dll
; #define IncludeAvDevice        ; avdevice-63.dll
; #define IncludeSwResample      ; swresample-7.dll
; #define IncludeSwScale         ; swscale-10.dll
; #define IncludeSDL2            ; SDL2.dll
; #define IncludeOpenAL32        ; OpenAL32.dll

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0374F101-3BDB-402D-ACDE-24B65D49202C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Dday Normandy
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64" specifies that Setup cannot run
; on anything but x64 (not supported in 6.2.2, commented out)
; ArchitecturesAllowed=x64
; "ArchitecturesInstallIn64BitMode=x64" requests 64-bit mode
; (not supported in 6.2.2, commented out)
; ArchitecturesInstallIn64BitMode=x64
ChangesAssociations=yes
DisableProgramGroupPage=yes
; ESTA ES LA LÍNEA CLAVE: Debe estar en 'no' para que aparezca la página de selección
DisableDirPage=no
; Permite que el usuario elija una ruta que no existe (la creará el instalador)
AllowNoIcons=yes
; Esto permite que el usuario instale incluso si no tiene derechos de admin en esa carpeta específica (opcional)
PrivilegesRequired=admin
LicenseFile=licencia.txt
InfoBeforeFile=pre-install.txt
InfoAfterFile=post-install.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=Output
OutputBaseFilename=DdayNormandy_Setup
SetupIconFile=icon.ico
SolidCompression=yes
WizardStyle=modern
WizardImageFile=wizard.bmp
; WizardSmallImageFile=small.bmp
; Esto hará que la imagen lateral no se estire feo
WizardImageStretch=yes

[Languages]
;Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Types]
Name: "full"; Description: "Instalación Completa (Mod + Todo el HD)"
Name: "minimal"; Description: "Instalación Básica (Solo el Mod)"
Name: "custom"; Description: "Personalizada"; Flags: iscustom

[Components]
; El componente base siempre se instala
Name: "base"; Description: "Archivos Esenciales del Mod"; Types: full minimal custom; Flags: fixed

; Grupo principal de HD (no tiene archivos asociados, sirve de título)
Name: "menu_hd"; Description: "Menu mejorado HD"; Types: full

; Subcomponentes (se usa el nombre del padre seguido de una barra \)
Name: "hd_pack_textures"; Description: "Texturas de Alta Resolución"; Types: full
Name: "hd_pack_models"; Description: "Modelos HD"; Types: full

[Files]
; --- EJECUTABLES PRINCIPALES ---
Source: "Quake2.exe"; DestDir: "{app}"; Components: base; Flags: ignoreversion
Source: "q2proded.exe"; DestDir: "{app}"; Components: base; Flags: ignoreversion

; --- DLLs ENGINE 64-bit ---
Source: "gamex86_64.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#ifdef IncludeDiscordSDK
Source: "discord_game_sdk.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeAvFormat
Source: "avformat-63.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeAvCodec
Source: "avcodec-63.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeAvUtil
Source: "avutil-61.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeAvFilter
Source: "avfilter-12.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeAvDevice
Source: "avdevice-63.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeSwResample
Source: "swresample-7.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeSwScale
Source: "swscale-10.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeSDL2
Source: "SDL2.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif
#ifdef IncludeOpenAL32
Source: "OpenAL32.dll"; DestDir: "{app}"; Components: base; Flags: ignoreversion
#endif

; --- CARPETA BASEQ2 ---
Source: "baseq2\*"; DestDir: "{app}\baseq2"; Components: base; Flags: ignoreversion recursesubdirs createallsubdirs

; --- CARPETA DDAY (gamex86.dll se inyecta en workflow) ---
Source: "dday\*"; DestDir: "{app}\dday"; Components: base; Flags: ignoreversion recursesubdirs createallsubdirs

; --- COMPONENTES OPCIONALES (HD PACK) ---
Source: "dday\texturas xshot.pak"; DestDir: "{app}\dday"; Components: hd_pack_textures; Flags: ignoreversion
Source: "dday\mastexturas.pak"; DestDir: "{app}\dday"; Components: hd_pack_textures; Flags: ignoreversion
Source: "dday\menu.pak"; DestDir: "{app}\dday"; Components: menu_hd; Flags: ignoreversion
Source: "dday\pak9.pak"; DestDir: "{app}\dday"; Components: hd_pack_models; Flags: ignoreversion

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\Quake2.exe"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\Quake2.exe"; Tasks: desktopicon

[UninstallDelete]
; Borra archivos generados por el juego que el instalador no conocía
Type: filesandordirs; Name: "{app}\baseq2\*.log"
Type: filesandordirs; Name: "{app}\dday\*.log"
Type: filesandordirs; Name: "{app}\dday\demos"
Type: filesandordirs; Name: "{app}\dday\screenshots"
; Borra la carpeta completa si el usuario desinstala todo
Type: filesandordirs; Name: "{app}\baseq2"
Type: filesandordirs; Name: "{app}\dday"

[Code]
// Mensaje que aparece ANTES de empezar a desinstalar
function InitializeUninstall(): Boolean;
begin
  Result := MsgBox('¿Estás seguro de que deseas eliminar Dday Normandy Edición Chile?' + #13#10 +
            'Esto borrará el mod y tus configuraciones.' + #13#10#13#10 +
            'Si tienes dudas o problemas, visita: www.dday.cl', 
            mbConfirmation, MB_YESNO) = IDYES;
  if not Result then
    MsgBox('Desinstalación cancelada.', mbInformation, MB_OK);
end;

// Mensaje que aparece DESPUÉS de terminar la desinstalación
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    MsgBox('Dday Normandy ha sido eliminado correctamente.' + #13#10#13#10 +
           'Esperamos verte de vuelta pronto en las trincheras.' + #13#10 +
           'Visítanos en www.dday.cl para nuevas versiones.', 
           mbInformation, MB_OK);
  end;
end;

[Run]
Filename: "{app}\Quake2.exe"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

